# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HRA Tool Community
email: info@ideacrew.com
description: >- # this means to ignore newlines until "baseurl:"
  The HRA Tool Community site is a resource for state-based Exchanges 
  who use the consumer decision support HRA Tool application for determining 
  the affordability of employer-offered HRAs: including  
  Individual Coverage Health Reimbursement Arrangements (ICHRA) and 
  Qualified Small Employer Health Reimbursement Arrangements (QSEHRA).
baseurl: "/hra_calculator" # the subpath of your site, e.g. /blog
url: "https://ideacrew.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
twitter_username: ideacrew.inc
github_username:  ipublic

# Footer content appears at the bottom of every page's main content
footer_content: "Support for this tool was provided by the Robert Wood Johnson Foundation. The views expressed here do not necessarily reflect the views of the Foundation."
# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag



permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
